// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vadhwoknebojprawjwmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhZGh3b2tuZWJvanByYXdqd215Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTg3NDYsImV4cCI6MjA3MjAzNDc0Nn0.h0i1rG_DCzVmUY7SOYoW-ecZhurgccx-eADd_1JZyuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});