// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukevbvdjgeukzjdxbsfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZXZidmRqZ2V1a3pqZHhic2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjkwMTYsImV4cCI6MjA2ODYwNTAxNn0.u5cvCFUt06v0nhB1TWtgFqdxfWWZelnIFmoKifhGoOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});