// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvfdyckisluzgunpcsyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2ZmR5Y2tpc2x1emd1bnBjc3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjE5MzIsImV4cCI6MjA3MTE5NzkzMn0.O5xXsxe1cQMNyhO4KxFajmqPhVCEOO8EaxhcXcwe8rA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});